In [ ]:
#created at 20250423

In [ ]:
#Advanced numpy operations

In [1]:
print("\n === Advanced numpy operations ===")


 === Advanced numpy operations ===


In [5]:
import pandas as pd
import numpy as np

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
print(f"Transpose:{arr.T}")

Transpose:[[1 4]
 [2 5]
 [3 6]]


In [9]:
print(f"Reshape:\n {arr.reshape(3, 2)}")

Reshape:
 [[1 2]
 [3 4]
 [5 6]]


In [10]:
print(f"stack:\n {np.vstack((arr, arr))}")

stack:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
