In [ ]:
#created at 20250421

In [ ]:
#Basic Numpy Arrays

In [1]:
print("\n === Basic Numpy Arrays ===")


 === Basic Numpy Arrays ===


In [3]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])

In [10]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
print(f"1D Array: {arr1}")

1D Array: [1 2 3 4 5]


In [12]:
print(f"2D Array:\n{arr2}")

2D Array:
[[1 2 3]
 [4 5 6]]


In [14]:
print(f"arry shapee:{arr2.shape}")

arry shapee:(2, 3)


In [15]:
print(f" Array Dimensions:{arr2.ndim}")

 Array Dimensions:2


In [ ]:
#Array Creation Methods

In [16]:
print("\n Array Creation Methods ")


 Array Creation Methods 


In [22]:
zeros = np.zeros((2, 3))

In [23]:
ones = np.ones((2,2))

In [24]:
random_arr = np.random.rand(3, 3)

In [25]:
range_arr = np.arange(0, 10, 2)

In [26]:
print(f"zeros:{zeros}")

zeros:[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
print(f"ones:{ones}")

ones:[[1. 1.]
 [1. 1.]]


In [28]:
print(f"Random:{random_arr}")

Random:[[0.59081775 0.0935357  0.08868859]
 [0.58074852 0.06797903 0.22512338]
 [0.11001029 0.88341247 0.68778503]]


In [29]:
print(f"range:{range_arr}")

range:[0 2 4 6 8]
